Revert "Enable WebGPU on Skia Renderer"
This reverts commit 5c675fd95d32f345a68da9212c1c5692e500fd0d.

Reason for revert: Test failures on GPU FYI bots

Test: SharedImageBackingFactoryD3DTest.GL_SkiaGL/0
Error: "Unable to create shared handle for DXGIResource"
Bots:
https://ci.chromium.org/p/chromium/builders/ci/Win7%20FYI%20Debug%20%28AMD%29
https://ci.chromium.org/p/chromium/builders/ci/Win7%20FYI%20Release%20%28AMD%29
https://ci.chromium.org/p/chromium/builders/ci/Win7%20FYI%20x64%20Release%20%28NVIDIA%29
https://ci.chromium.org/p/chromium/builders/ci/Win7%20FYI%20x64%20Release%20%28NVIDIA%29

Original change's description:
> Enable WebGPU on Skia Renderer
> 
> Implement SharedImageBackingD3D::ProduceSkia and supporting methods.
> 
> Bug: 1021118,1002316
> Change-Id: Ia699bddfa08469b9e151018eca6c5206620cb731
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1938707
> Commit-Queue: Rafael Cintron <rafael.cintron@microsoft.com>
> Reviewed-by: Sunny Sachanandani <sunnyps@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#720722}

TBR=zmo@chromium.org,sunnyps@chromium.org,rafael.cintron@microsoft.com

Change-Id: Ie43049a059a0c7545676ba3fbff90025fa75ffc4
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1021118, 1002316
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/1947930
Reviewed-by: Geoff Lang <geofflang@chromium.org>
Commit-Queue: Geoff Lang <geofflang@chromium.org>
Cr-Original-Commit-Position: refs/heads/master@{#720984}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: fcfd57a77968536266ce01fdb4765f977ab59eb8