Revert of command_buffer_gles2: Implement EGL default Display as a global object (patchset #25 id:480001 of https://codereview.chromium.org/1714883002/ )
Reason for revert:
Still failing on official chromeos builders:
egl_native_windowless.cc:79:69: error: cannot convert 'tcu::egl::Display' to 'EGLDisplay {aka void*}' for argument '1' to 'void CommandBufferGLESSetNextCreateWindowSurfaceCreatesPBuffer(EGLDisplay, EGLint, EGLint)'

Complete output:

chromeos-chrome-52.0.2720.0_alpha-r1: FAILED: i686-pc-linux-gnu-g++ -B/usr/x86_64-pc-linux-gnu/i686-pc-linux-gnu/binutils-bin/2.25.51-gold -MMD -MF obj/gpu/khronos_glcts_support/native/tcutil_platform_windowless.egl_native_windowless.o.d -DV8_DEPRECATION_WARNINGS '-DDEQP_TARGET_NAME="chrome-gpu-command-buffer"' -DDEQP_SUPPORT_GLES2=1 -DDEQP_SUPPORT_EGL=1 -DGTF_API=GTF_GLES20 -D_FILE_OFFSET_BITS=64 -DGOOGLE_CHROME_BUILD -DENABLE_RLZ -DCOMPONENT_BUILD -DUI_COMPOSITOR_IMAGE_TRANSPORT -DUSE_AURA=1 -DUSE_ASH=1 -DUSE_PANGO=1 -DUSE_CAIRO=1 -DUSE_CRAS=1 -DUSE_OZONE=1 -DUSE_DEFAULT_RENDER_THEME=1 -DUSE_LIBJPEG_TURBO=1 -DIMAGE_LOADER_EXTENSION=1 -DENABLE_WEBRTC=1 -DENABLE_MEDIA_ROUTER=1 -DUSE_PROPRIETARY_CODECS -DENABLE_PEPPER_CDMS -DENABLE_NOTIFICATIONS -DENABLE_TOPCHROME_MD=1 -DENABLE_WAYLAND_SERVER=1 -DUSE_UDEV -DENABLE_TASK_MANAGER=1 -DENABLE_EXTENSIONS=1 -DENABLE_PDF=1 -DENABLE_PLUGINS=1 -DENABLE_SESSION_SERVICE=1 -DENABLE_THEMES=1 -DENABLE_AUTOFILL_DIALOG=1 -DENABLE_PROD_WALLET_SERVICE=1 -DENABLE_PRINTING=1 -DENABLE_PRINT_PREVIEW=1 -DENABLE_SPELLCHECK=1 -DENABLE_CAPTIVE_PORTAL_DETECTION=1 -DENABLE_APP_LIST=1 -DENABLE_SUPERVISED_USERS=1 -DENABLE_MDNS=1 -DENABLE_SERVICE_DISCOVERY=1 -DENABLE_HANGOUT_SERVICES_EXTENSION=1 -DV8_USE_EXTERNAL_STARTUP_DATA -DFULL_SAFE_BROWSING -DSAFE_BROWSING_CSD -DSAFE_BROWSING_DB_LOCAL -D_XOPEN_SOURCE=500 -DUSE_LIBPCI=1 -DUSE_NSS_CERTS=1 -DOS_CHROMEOS=1 -DNDEBUG -DNO_UNWIND_TABLES -DOFFICIAL_BUILD -DNVALGRIND -DDYNAMIC_ANNOTATIONS_ENABLED=0 -Igen -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos -I../../../../../../../home/chrome-bot/chrome_root/src/gpu -I../../../../../../../home/chrome-bot/chrome_root/src -I../../../../../../../home/chrome-bot/chrome_root/src/skia/config -Igen/angle -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/delibs/debase -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/delibs/depool -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/delibs/dethread -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/delibs/deutil -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/delibs/decpp -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/qphelper -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/common -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/opengl -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/opengl/wrapper -I../../../../../../../home/chrome-bot/chrome_root/src/third_party/khronos_glcts/framework/egl -pthread -fno-strict-aliasing -Wno-extra -Wno-unused-parameter -Wno-missing-field-initializers -fvisibility=hidden -pipe -fPIC -g -Wno-unused-local-typedefs -msse2 -mfpmath=sse -mmmx -m32 --sysroot=/build/x86-alex -O2 -fno-ident -fdata-sections -ffunction-sections -fno-unwind-tables -fno-asynchronous-unwind-tables -g -march=i686 -pipe -march=i686 -pipe -pipe -march=atom -mtune=atom -mfpmath=sse -D__google_stl_debug_vector=1 -fno-threadsafe-statics -fvisibility-inlines-hidden -Wno-deprecated -std=gnu++11 -Wno-narrowing -Wno-literal-suffix  -c ../../../../../../../home/chrome-bot/chrome_root/src/gpu/khronos_glcts_support/native/egl_native_windowless.cc -o obj/gpu/khronos_glcts_support/native/tcutil_platform_windowless.egl_native_windowless.o
chromeos-chrome-52.0.2720.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/gpu/khronos_glcts_support/native/egl_native_windowless.cc: In member function 'virtual tcu::NativeWindow* egl::native::windowless::Platform::createWindow(tcu::NativeDisplay&, EGLConfig, const EGLint*, int, int, qpVisibility)':
chromeos-chrome-52.0.2720.0_alpha-r1: ../../../../../../../home/chrome-bot/chrome_root/src/gpu/khronos_glcts_support/native/egl_native_windowless.cc:79:69: error: cannot convert 'tcu::egl::Display' to 'EGLDisplay {aka void*}' for argument '1' to 'void CommandBufferGLESSetNextCreateWindowSurfaceCreatesPBuffer(EGLDisplay, EGLint, EGLint)'
chromeos-chrome-52.0.2720.0_alpha-r1:                                                                height);

Original issue's description:
> command_buffer_gles2: Implement EGL default Display as a global object
>
> Make EGL Display a global. eglGetDisplay(EGL_DEFAULT_DISPLAY) will
> return the same object.
>
> Store EGL state in a new thread-local object (ThreadState). One
> display, multiple surfaces, multiple contexts.
>
> Fix the currently implemented entry points to return specified errors
> and behave as specified. Notable changes:
> * eglGetDisplay() does not create new displays for each invocation
> * eglTerminate() invalidates the created egl objects but leaves the
>   current context intact as specified
> * eglMakeCurrent() is implemented more correctly with refcount semantics
> * eglQueryStrings() works without display for some names
> * eglReleaseThread() is implemeted
> * Config are now separate for pbuffers and windows, so that contexts
>   can be created separate from surfaces
> * Context can be made current with different surfaces
> * Catches errors related to context being set current to multiple
>   threads
> * Tries to be thread-safe
>
> In the implementation, the Display contains a lock ensuring all thread
> accesses are consistent. All functions using or changing thread-local
> state have explicit egl::ThreadState parameter.
>
> BUG=581634
> CQ_INCLUDE_TRYBOTS=tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Committed: https://crrev.com/de9aa3be41bca094454babbd62907815fad7f5c2
> Cr-Commit-Position: refs/heads/master@{#377535}
>
> Committed: https://crrev.com/7b01a0867be0895009b120f37fcd4166a84f404b
> Cr-Commit-Position: refs/heads/master@{#386613}
>
> Committed: https://crrev.com/f9d5c7e6fd53570c0decc63e8ec51d30e0701c89
> Cr-Commit-Position: refs/heads/master@{#387871}
>
> Committed: https://crrev.com/2a8624e1d4f8a82a9a8ce6b55fa5a48be09b9e09
> Cr-Commit-Position: refs/heads/master@{#388745}

TBR=piman@chromium.org,kbr@chromium.org,kkinnunen@nvidia.com
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=581634

Review-Url: https://codereview.chromium.org/1929973003
Cr-Original-Commit-Position: refs/heads/master@{#390406}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: e13ac01fdeed60d4f8dde9d6d595ccf81e1e7fac