fix missing deps for gpu/ipc/common/interfaces_cpp_sources
```
ukai@ukai ...src/chromium/src % cat out/dep/args.gn
is_debug = false
use_remoteexec = true
use_reclient = false
use_siso = true
ukai@ukai ...src/chromium/src % gn clean out/dep
ukai@ukai ...src/chromium/src % siso ninja --verbose_failures=false -C out/dep obj/gpu/ipc/common/interfaces_cpp_sources/exported_shared_image.mojom.o
ninja: Entering directory `out/dep'
reapi instance: projects/rbe-chrome-untrusted/instances/default_instance
 4.45s load siso config
 7.77s Regenerating ninja files
 3.61s reloading
[3373/3374] 1m06.68s F CXX obj/gpu/ipc..._sources/exported_shared_image.mojom.o
FAILED: ee8f440f-7cd9-4be3-b132-6b029e33cdb2 "./obj/gpu/ipc/common/interfaces_cpp_sources/exported_shared_image.mojom.o" CXX obj/gpu/ipc/common/interfaces_cpp_sources/exported_shared_image.mojom.o
err: exit=1
../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -M  ...(too long)
Use '--verbose_failures' to see the command lines
build step: cxx "./obj/gpu/ipc/common/interfaces_cpp_sources/exported_shared_image.mojom.o"
siso_rule: clang/cxx
stderr:
In file included from gen/gpu/ipc/common/exported_shared_image.mojom.cc:12:
In file included from gen/gpu/ipc/common/exported_shared_image.mojom.h:31:
In file included from gen/gpu/ipc/common/shared_image_metadata.mojom.h:41:
In file included from ../../gpu/ipc/common/shared_image_metadata_mojom_traits.h:9:
In file included from ../../gpu/command_buffer/client/client_shared_image.h:19:
../../gpu/command_buffer/client/shared_image_interface.h:21:10: fatal error: 'gpu/ipc/common/shared_image_pool_client_interface.mojom.h' file not found
   21 | #include "gpu/ipc/common/shared_image_pool_client_interface.mojom.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

build failed
local:771 remote:15 cache:2588 fallback:0 retry:0 skip:1532
reapi: ops: 2743(err:109) / r:7360(err:0) 187.33MiB / w:41(err:0) 20.50KiB
fs: ops: 423460(err:179305) / r:164029(err:0) 10.56GiB / w:5444(err:0) 294.66MiB

1m07.00s Build Failure: 3374 done 1 failed 0 remaining - 50.36/s
 1 steps failed: exit=1
see ./out/dep/siso_output for full command line and output
 or ./out/dep/siso.INFO
use ./out/dep/siso_failed_commands.sh to re-run failed commands
```

it depends on ":shared_image_pool_client_interface".

Bug: 414713295
Change-Id: I5d2ac05ce99c0dc568494108cbb504d0f8532c72
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/6497955
Commit-Queue: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takashi Toyoshima <toyoshim@chromium.org>
Auto-Submit: Fumitoshi Ukai <ukai@google.com>
Reviewed-by: Takuto Ikuta <tikuta@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1454230}
NOKEYCHECK=True
GitOrigin-RevId: 5f9afb9f28603a3e4254e5f70e34be04903715d7