Revert "jni_zero: Fixing up more broken multiplexing instances"
This reverts commit 43c68b0aadee5aea59b467daefeb1572e694240a.

Reason for revert: Breaks internal build
See https://ci.chromium.org/ui/p/chrome/builders/ci/chromium-internal-arm-builder-rel/9905/overview

java.io.IOException: error reading obj/ui/base/select_file_dialog_jni_headers_java.processed.jar
	at com.google.turbine.binder.ClassPathBinder.bindClasspath(ClassPathBinder.java:69)
	at com.google.turbine.main.Main.bind(Main.java:272)
	at com.google.turbine.main.Main.compile(Main.java:158)
	at com.google.turbine.main.Main.compile(Main.java:133)
	at com.google.turbine.main.Main.main(Main.java:89)
Caused by: java.nio.file.NoSuchFileException: obj/ui/base/select_file_dialog_jni_headers_java.processed.jar

Original change's description:
> jni_zero: Fixing up more broken multiplexing instances
>
> These are a non-exhaustive set of cases where multiplexing broke
> because we are depending on a generate_jni target without depending on
> the corresponding .cc file which includes the _jni.h file.
>
>
> Bug: 40612925
> Change-Id: I9ce6261998ab0614ee33ba0895b9dee510ce02f7
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5478018
> Owners-Override: Andrew Grieve <agrieve@chromium.org>
> Commit-Queue: Sam Maier <smaier@chromium.org>
> Reviewed-by: Andrew Grieve <agrieve@chromium.org>
> Cr-Commit-Position: refs/heads/main@{#1291845}

Bug: 40612925
Change-Id: If966d17bbd232f683d1c2e2beae9035890aa1f5e
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/5483669
Auto-Submit: Patrick Noland <pnoland@chromium.org>
Bot-Commit: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Commit-Queue: Rubber Stamper <rubber-stamper@appspot.gserviceaccount.com>
Owners-Override: Patrick Noland <pnoland@chromium.org>
Cr-Commit-Position: refs/heads/main@{#1291935}
NOKEYCHECK=True
GitOrigin-RevId: 3bff690c506fa056e812110a19d98073e6263e94