Revert of Copy GPU workaround flags from browser to GPU process (patchset #4 id:20002 of https://codereview.chromium.org/2644733005/ )
Reason for revert:
There is a gpu_unittests failure on OSX:
AssertionError: Browser and GPU process list of driver bugworkarounds are not equal

Starting from https://build.chromium.org/p/chromium.gpu.fyi/builders/Mac%20Retina%20Release/builds/10498

This CL seems like the culprit, reverting.

Original issue's description:
> Copy GPU workaround flags from browser to GPU process
>
> BUG=682912
> CQ_INCLUDE_TRYBOTS=master.tryserver.chromium.linux:linux_optional_gpu_tests_rel;master.tryserver.chromium.mac:mac_optional_gpu_tests_rel;master.tryserver.chromium.win:win_optional_gpu_tests_rel
>
> Review-Url: https://codereview.chromium.org/2644733005
> Cr-Commit-Position: refs/heads/master@{#447356}
> Committed: https://chromium.googlesource.com/chromium/src/+/ded062d6c02a0cbfa89c90dae364c48f9118a328

TBR=kbr@chromium.org,zmo@chromium.org,kainino@chromium.org
# Skipping CQ checks because original CL landed less than 1 days ago.
NOPRESUBMIT=true
NOTREECHECKS=true
NOTRY=true
BUG=682912

Review-Url: https://codereview.chromium.org/2666353002
Cr-Original-Commit-Position: refs/heads/master@{#447523}
Cr-Mirrored-From: https://chromium.googlesource.com/chromium/src
Cr-Mirrored-Commit: b684241f1f14948c108d715ebe7c5a9427a9fcd0