Fix regexp in software renderer json
This CL fixes missing escape for bracket. Without it there is a lot of
logs on Android Lollipop bot, they don't make bot go red though.

Example:
https://chromium-swarm.appspot.com/task?id=564185a8ca9e7c11

../../third_party/re2/src/re2/re2.cc:205: Error parsing 'ANGLE
(Imagination Technologies, PowerVR .*': missing ): ANGLE (Imagination
Technologies, PowerVR .*
../../third_party/re2/src/re2/re2.cc:890: Invalid RE2: missing ): ANGLE
(Imagination Technologies, PowerVR .*

Bug: 1203652,1221321
Change-Id: I5b6f9a4045bf9e6b0ccef945bc656dd9f83f3b95
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3188530
Reviewed-by: Peng Huang <penghuang@chromium.org>
Commit-Queue: Vasiliy Telezhnikov <vasilyt@chromium.org>
Cr-Commit-Position: refs/heads/main@{#925741}
NOKEYCHECK=True
GitOrigin-RevId: 41ebbe8c58991a2772d2ccc6febb64636386f6b5