IWYU: missing include for usage of std::unique_ptr in vulkan_function_pointers.h
Added <memory> include.

Fixes build error with libstdc++:
    ./../gpu/vulkan/vulkan_function_pointers.h:77:32: error: ‘unique_ptr’ is not a member of ‘std’
       77 |   base::flat_map<VkQueue, std::unique_ptr<base::Lock>> per_queue_lock_map;
          |                                ^~~~~~~~~~

Bug: 957519
Change-Id: Iefdf89112d5f441071135731cdbc057ff7ec0f3a
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/3499100
Reviewed-by: Peng Huang <penghuang@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/main@{#977028}
NOKEYCHECK=True
GitOrigin-RevId: 2427780fdab86e70e4e3152c3aa40b161fe9c1a4